### ISSUE TITLE
GetMemberGroups and its return value should be a list

### ISSUE THREAD

**Issue by avasay** [kylegregory/EmmaSharp#1]
First of all, I'm new to REST programming, and I would like to thank you very much for this wonderful API wrapper. Without this, I'd probably be pulling out my teeth to get Emma API to work. 

Anyway, I was trying to get the GetMemberGroups method to work, to test if I could get a simple GET request. To make the long story short, I had to change the return value from ```MemberGroups``` to ```List<Groups>``` to get it to work, because Emma returns an array, not an object. Otherwise, ```JsonConvert.DeserializeObject``` will throw an exception. So Emma returns something like this:
```
[ 
{    
	\"active_count\": 2,    
	\"deleted_at\": null,    
	\"error_count\": 0,   
	\"optout_count\": 0,    
	\"group_type\": \"g\",    
	\"member_group_id\": xxxxxxx,    
	\"purged_at\": null,    
	\"account_id\": xxxxxxx,    
	\"group_name\": \"Microsite Marketing Form\"  
}
]
```
So, the method works now (BTW, I'm not forking the project, I just downloaded the zip and doing this on my own). 

The next thing I have to tackle is the ```AddOrUpdateSingleMember``` method, which I believe  corresponds to 
```
POST /#account_id/members/add 
```
API in the Emma docs. When I called ```AddOrUpdateSingleMember```, it throws a ```Unable to parse JSON request``` exception. I believe that the data that I'm trying to pass (i.e., ```MemberGroups```, ```List<Field>```) are in the wrong format? 

Because I need a method to add a member to Emma (we have a web page that simply prompts user to enter her name and email address, and then I send these data to Emma), and because I can't figure out the problem with ```AddOrUpdateSingleMember```, I probably just need to pass a raw Json data to Emma (I was able to create a member passing a raw Json object using Google Chrome's Advanced REST Client). 

Any thoughts on this problem? Has Emma changed something that the API wrapper was not able to get updated with? 

Thanks,
Al

**Comment by kylegregory** [comment]
@avasay Thanks for the message. I've only been working on the wrapper in my spare time, so there are quite a few untested holes.

You're right, GetMemberGroups should be List<Group>. I've been updating this slowly throughout the project, and I'll update the repository soon.

Most POST, PUT, and DELETE calling methods have been untested thus far. The largest issue being that I've had trouble taking all of Emma's required and optional parameters to work nicely with a POST command, as RestSharp dictates. They all must be encapsulated within the Body of the request, rather than Parameters as I have used them. Examples show this as interchangeable, but real world usage begs to differ. 

I've worked on getting AddOrUpdateSingleMember to work and when I'm happy with at least the basic functionality, that will be in the next update as well. My goal will be to get most methods working soon.

**Comment by avasay** [comment]
I'll keep on checking for updates, especially for AddOrUpdateSingleMember. Thanks so much for your work on this.

**Comment by avasay** [comment]
I ended up doing this for the AddOrUpdateSingleMember(). I created my own version of that method that doesn't use Field class. I figured that the minimum data that Emma needs to create a new member is "email" and "fields", just like this json string below:
{
  "fields": {
    "first_name": "Loren", 
    "last_name": "Malik"
  }, 
  "email": "lmalik@hotmail.com"
}

The parameter "List<Field> fields" in the original method doesn't seem to work because the Field class doesn't have "email" and "fields" objects.  So, I created a class that has those three properties. And my final code looks like this:

public status_add AddOrUpdateSingleMember_2(string memberEmail, string lname, string fname)
        {
            var request = new RestRequest(Method.POST);
            request.Resource = "/{accountId}/members/add";
            request.RequestFormat = DataFormat.Json;

            // Initialize Dictionary and Email
            member_data member = new member_data();
            member.email = memberEmail;

            // Initialize Member Name
            member_name name = new member_name();
            name.first_name = fname;
            name.last_name = lname;

            // Finally initialize fields to name
            member.fields = name;

            request.AddBody(member);

            return Execute<status_add>(request);
        }

And this worked! I was able to create a new member. I'm just using request.AddBody() instead of request.AddParameter(). And these are my data classes:

public class member_data
    {  
        public string email { get; set; }
        public member_name fields { get; set; }
    }

    public class member_name
    {
        public string first_name { get; set; }
        public string last_name { get; set; }
    }

So, I'm happy because really that's all I really want to do -- is to add a new member! Thanks!

**Comment by kylegregory** [comment]
I ended up using a Dictionary for Fields in case you wanted to support more than FName and LName. This is at least what I'm going with for the time being. I also did the `AddBody()` method a bit differently.
```C#
public MemberAdd AddOrUpdateSingleMember(string memberEmail, Dictionary<string, string> fields, string groupIds = "", bool fieldtriggers = false)
{
    var request = new RestRequest(Method.POST);
    request.Resource = "/{accountId}/members/add";
    request.RequestFormat = DataFormat.Json;
    request.AddBody(new { email = memberEmail, fields = fields, group_ids = groupIds, field_triggers = fieldtriggers });

    return Execute<MemberAdd>(request);
}
```
`memberEmail` and `fields` are required whereas `groupids` and `fieldtriggers` are not.

Thoughts? Improvements?

**Comment by avasay** [comment]
That's a LOT cleaner than what I'm doing :-).

**Comment by kylegregory** [comment]
I thought about a class, but since Fields can change depending on what you want to update, or if you have custom data fields in your audience, It ends up being a bit more reusable here. Of course if your code works for you, go for it.

I'll see about pushing an update and possibility outlining where I'm at/what's been tested.

**Comment by avasay** [comment]
Good point. Thanks and have a great weekend!

**Comment by avasay** [comment]
Thanks for the updates! Just downloaded the whole project and now testing AddOrUpdateSingleMember() method. It worked, and I was able to create a new member in our Emma account. The only thing that did not work is that it did not add my new member to the group ID that I specified. But, I got it to work by changing the type of the groupIds from "string" to List<string> in the parameter. So, 

AddOrUpdateSingleMember(string memberEmail, Dictionary<string, string> fields, List<string> groupIds, bool fieldtriggers = false)

List<int> works too for some reason, as that's how I first tested it with.

**Comment by kylegregory** [comment]
I'm still working on getting towards ```Members```. I've tested ```Fields```, ```Groups``` and most of ```Mailings```.

I took your suggestion (as you can see in ```Fields``` and ```Groups```) and I'm moving towards a class for Post/Put operations. So you'll define the URL prams and anything that Emma must have to complete the operation, then the data to be updated will be defined in the class. That way you can choose what fields are posted, the others either NULL or empty strings. So calls are subject to change in future updates, and this one will in future versions!

I've gotten tripped up on a few calls and needed clarification from the Emma team, because the documentation is light, and there are even calls that are not correct in Apigee.

For example ```UpdateMailingStatus```, the documentation says I should expect back the mailing's new status (which should be either a cancel, paused or ready or a representative short code). What is actually returned is a representation of the mailing itself. So i'm going back and building classes for those calls when that happens.

After I've gotten at least a bulk of the calls tested (the ones I can), I'll go for an "official" beta release, and then put up on NuGet. It should be a bit easier to manage from there, and less breaking changes.

Keep testing the calls you need and let me know of any issues. I'm leaving this open until I've at least gotten through ```Members```.

**Comment by avasay** [comment]
By the way, I modified my reply earlier. I wasn't aware that I wasn't using a code block for my codes, and they weren't displaying correctly.

Yes, Emma's API docs are very parse! I'm amazed at how much you've accomplished. I will definitely let you know of any more issues in the future. At the moment, the only method I am using so far is adding a member. I think I will be using that UpdateMailingStatus eventually. Thanks for working on it.

**Comment by kylegregory** [comment]
@avasay Per number 2 in [your comment](https://github.com/kylegregory/EmmaSharp/issues/1#issuecomment-172960262), I've fixed those. Happy for any assistance.

**Comment by kylegregory** [comment]
Hey @avasay ,

I had some time to start working on Members. Have a look at the most recent commit and see what you think. I've worked on [AddOrUpdateSingleMember](https://github.com/kylegregory/EmmaSharp/blob/master/EmmaSharp/Methods/Members.cs#L162). See how it works on your end. I'm open to suggestions.

**Comment by avasay** [comment]
I just finished testing your new updates for the AddOrUpdateSingleMember method, and everything is working perfectly! I also liked the fact that you made the interface simpler. THANKS very much!

**Comment by kylegregory** [comment]
@avasay,

Great and good to know. I'm going to keep plugging away, but if there's another method I should look at, let me know. I've documented progress on the ReadMe.

**Comment by avasay** [comment]
I definitely will, thanks!
