### ISSUE TITLE
Get Member by Field Value?

### ISSUE THREAD

**Issue by tjdavis1111** [kylegregory/EmmaSharp#41]
Kyle,
Does the Emma API have a method for retrieving members by field value?  The only way that I've figured out how to do this is to get all members and then filter the list by the desired field's value.  Unfortunately, with 12.5K members, that's 25 GETS @ 500 per.  The resulting response time can be measured in minutes.

Thx.

**Comment by kylegregory** [comment]
@tjdavis1111 

The only way I know of is to create a `Search` using the API and then once build retrieve a list of members matching the search.

[Search Endpoints](https://api.myemma.com/api/external/searches.html)
[Search Syntax](https://api.myemma.com/member_search.html)

Note that the wrapper currently [doesn't support creating or updating searches](#14) because of an issue believed to be on Emma's end. If you do some digging and find out otherwise, let me know.

**Comment by tjdavis1111** [comment]
Thanks for the reply.  Just found Searches.
